### PR TITLE
release and kill test

### PR DESCRIPTION
**Pull request by Mapsee**
Completed the tests for the release mariogatchi feature: 
involves tests for the RemoveMariogatchiFactory: KillMariogatchiFactory and TransferMariogatchiFactory
involves tests for adding and removing mariogatchi: MariogatchiManager
Output boundary tests: RemoveMariogatchiDisplayer and RemoveMariogatchiPresenter

### CODE REVIEW

**Review by nishi003 — CHANGES_REQUESTED** [review]
slay (those mariogatchis). these tests look good and seem to cover all the test cases. what happens when the user has no mariogatchis?

**Comment by Mapsee** [comment]
> slay (those mariogatchis). these tests look good and seem to cover all the test cases. what happens when the user has no mariogatchis?

Hello! Thank you for the inquiry
MariogatchiManagerTest: returns False, see ReleaseMariogatchi_thenisFalse()

I will add additional cases for that in the factories.

**Comment by Mapsee** [comment]
> slay (those mariogatchis). these tests look good and seem to cover all the test cases. what happens when the user has no mariogatchis?

Added new test cases, thank you for your input :D

**Review by Grace199 — APPROVED** [review]

**Review by nishi003 — APPROVED** [review]
idk why i requested changed, this looks good

**Review by Grace199 — APPROVED** [review]

**Review by adimaggio2021 — APPROVED** [review]

**Pull request merged**
