### PR TITLE
1 feature 1 login logout

### LINKED ISSUE #1: Feature 1: Login, logout
Create a database structure and an authentication class. Allow creating and verifying user accounts.

### PR DESCRIPTION
**Pull request by SpecialThing44**
Made blank entity classes, added a couple methods in account, made the authenticator class with some filler code for the missing hash methods.

### CODE REVIEW

**Review by Samuel-Glasroth — COMMENTED** [review]
Very good implementation, it does what it should do
Naming convention issue inside vaildPassword function (you are using snake case instead of camel case

**Review by adimaggio2021 — DISMISSED** [review]
Good progress

**Review by Najimsensei — DISMISSED** [review]
Well done, the authentication runner looks runnable

**Comment by nishi003** [comment]
Well-written code, good progress

**Review by nishi003 — DISMISSED** [review]
Well-written and readable, good progress

**Review by Grace199 — DISMISSED** [review]
Great work Spencer! Absolutely perfect, couldn't have done better myself. Completely adheres to the SOLID principles.

**Review by Samuel-Glasroth — DISMISSED** [review]
All good

**Review by adimaggio2021 — APPROVED** [review]
Best code ever!!

**Review by Samuel-Glasroth — APPROVED** [review]
All good

**Review by nishi003 — APPROVED** [review]
Wonderful work! Best code I've seen in my 18 years and 11 months and 8 days of life, I cried.

**Review by Grace199 — APPROVED** [review]
Wow. Stunning code. If I could approve it twice I would.

**Pull request merged**
