### PR TITLE
6 feature 6 changing environment

### LINKED ISSUE #6: Feature 6: Changing environment

### PR DESCRIPTION
**Pull request by nishi003**
Action: added Action enum containing all the types/categories of the different actions, the actions so far only have two properties, whether they need an item and the list of statistics the action impacts.

Environment: no longer has abstract getter methods or default constructor, Environment constructor takes name and actionList arguments, actionList is now of type List<Action> rather than List<String> as it was before. 

Environment Subclasses: simplified constructors now use super(), no overridden getter methods

### CODE REVIEW

**Review by SpecialThing44 — CHANGES_REQUESTED** [review]
Check camelCase on methods in action. Otherwise, I think it looks good and works according to the specification. Action enum was a good idea.

**Review by nishi003 — COMMENTED** [review]
CamalCase for Action enum getter methods

**Review by nishi003 — COMMENTED** [review]
Samuel a Spencer requests implemented

**Review by Mapsee — DISMISSED** [review]
Code looks great! I suggest adding comments on what each method does, including the subclasses for Environment (Forest, Home, Park), just for extra specification and caution :)

**Review by Grace199 — DISMISSED** [review]
I am a bit confused about the Action enum and why there is a constructor for it as it seems to only initialize one Action enum when there are 8 that have been declared. Although I might just be confused about how enums work. 

Also, I think that the Action's should be more general. Since these are going to be eligible actions in the Environment itself, I think it would be more useful to control actions such as "UseItem", "OpenInventory" etc. More specific actions (like using a "teachable" item) can just be passed onto their specific use cases where it can decide if it can be used or not. This way we can avoid adding more and more Action enums to the game if we want to add some action or item that does not necessarily fall under one of the enums, or we want it to be accessible to the user in a certain environment, despite it being a "TRAINABLE", for example. 

Otherwise, everything looks good.

**Review by Grace199 — DISMISSED** [review]
Looks great.

**Review by Mapsee — DISMISSED** [review]
Code looks good and great changes on the comments!

**Review by adimaggio2021 — DISMISSED** [review]
Good clean implementation with nothing unnecessary. I think we'll be adding to the environment classes later, but we have a solid start here.

**Review by Samuel-Glasroth — CHANGES_REQUESTED** [review]
variables that have the final modifier should be all caps and not using camelcase

**Review by Samuel-Glasroth — DISMISSED** [review]
Looks good for now

**Review by Grace199 — DISMISSED** [review]
Looks great

**Review by SpecialThing44 — COMMENTED** [review]
Looks good

**Review by SpecialThing44 — DISMISSED** [review]
Looks good

**Review by SpecialThing44 — DISMISSED** [review]
Still looks good from 9 minutes ago, gradle stuff will probably cause conflicts though

**Review by adimaggio2021 — DISMISSED** [review]
Same comment as last review.

**Review by Grace199 — DISMISSED** [review]
Fantastic.

**Review by Samuel-Glasroth — APPROVED** [review]
looks good

**Review by adimaggio2021 — APPROVED** [review]
Same again.

**Review by SpecialThing44 — APPROVED** [review]
not much has changed :)

**Pull request merged**
