### PR TITLE
4 feature 4 mariogatchi statistics

### LINKED ISSUE #4: Feature 4: Mariogatchi statistics

### PR DESCRIPTION
**Pull request by vivekvzdsw**
Stats modified. The timerunner class needs to be reviewed for accuracy. Stats class save and load of the times need to be reviewed. Times.txt is used to save the last checked time and to calculate differences.

### CODE REVIEW

**Review by Grace199 — CHANGES_REQUESTED** [review]
I think it would be useful to have the reduceStat and increaseStat methods increase by any integer rather than a factor of 10. Or at least have separate methods that do this. The reason being is that often stats will change because an item is used, but each item will have unique effects. If statistics can only go up by factors of 10, this restricts what differences can exist between items of the same category ( i.e we may want to have 10 different food items that update the hunger bar in slightly different ways or "treats" that update happiness more than the regular food item).

Also, the statChange method cases for "feed", "bathe", "walk", "sleep", "train", and "play" may be unnecessary since these actions are exclusively item accessible, and as said above, each individual item will have its own unique effect on stats.

**Review by Grace199 — DISMISSED** [review]
Amazing.

**Review by adimaggio2021 — DISMISSED** [review]
I like the implementation of getStat

**Comment by vivekvzdsw** [comment]
Great!

**Review by Grace199 — DISMISSED** [review]
Great stuff.

**Review by SpecialThing44 — DISMISSED** [review]
Generally looks good, follows CA and case convention. Package handling can be resolved later. Consider using enums instead of strings for switch cases, which you can then reuse. Might be possible to merge reduceStat and increaseStat into one changeStat with a bool. Not sure whats going on with statChange given I thought values were supposed to come from items. Also the two different decay functions should be resolved. Outside of the Statistics class I think its good.

**Review by adimaggio2021 — DISMISSED** [review]

**Review by SpecialThing44 — APPROVED** [review]
Looks better based on what I suggested, good stuff.

**Review by adimaggio2021 — APPROVED** [review]

**Review by Najimsensei — APPROVED** [review]
Good with the code I approve of the merge

**Pull request merged**
