### PR TITLE
25 controller finalization authentication tests

### PR DESCRIPTION
**Pull request by SpecialThing44**
Program compiles, starting controller test, fixed merge issues.

### CODE REVIEW

**Review by Grace199 — APPROVED** [review]
Great Work!

**Review by Mapsee — APPROVED** [review]
great job compiling the program

**Review by Grace199 — APPROVED** [review]
Great Work!

**Review by nishi003 — APPROVED** [review]
slay code

**Review by adimaggio2021 — APPROVED** [review]
It compiles 👍

**Pull request merged**
