### PR TITLE
25 controller finalization authentication tests

### LINKED ISSUE #25: Controller finalization, authentication tests.

### PR DESCRIPTION
**Pull request by SpecialThing44**
Input Controller is done except for find Mariogatchi, code is better documented, authenticator and game tests pass.

### CODE REVIEW

**Review by nishi003 — DISMISSED** [review]
Good work with the code! These tests will help us ensure our code is working as we planned.

**Review by Grace199 — DISMISSED** [review]

**Review by nishi003 — DISMISSED** [review]
good job implementing the controller, everything should run smoothly after these are merged to the main branch

**Review by nishi003 — DISMISSED** [review]
Good change to the code, I was wondering about it in your last pull request but this really cleared up my concerns

**Review by nishi003 — APPROVED** [review]
good typo fix spencer

**Review by Grace199 — APPROVED** [review]
Good work.

**Review by adimaggio2021 — APPROVED** [review]

**Pull request merged**
