### PR TITLE
I added implemented the Mariogatchi class as well as the CatchMarioga…

### LINKED ISSUE #3: Feature 3: Finding new Mariogatchi

### PR DESCRIPTION
**Pull request by Najimsensei**
…tchi user case. You will also find slight changes in the User class in order to fit my user AddMariogatchiRunner.

### CODE REVIEW

**Review by Mapsee — DISMISSED** [review]
Add comments for each of your methods for specification and caution. Check your AddMariogatchiInputBoundary for a spelling error in the comment. 

Must be implemented:
CatchMariogatchi use case calls MariogatchiManager (a use case to add a Mariogatchi to a users collection of Mariogatchis) so that the User can add a Mariogatchi to their collection once they have catched it.
AddMariogatchi(User user, Mariogatchi mariogatchi) <- is the method
See [MariogatchiManager](https://github.com/CSC207-2022F-UofT/course-project-mariogatchi/pull/19/files#diff-816c20f9889b9e4cd39b4f4dc99de6161c8aea5dffcabb32dd986f56e7f14d93)

Some extra implementation ideas (optional but cool) 
CatchMariogatchi can call the TransferFactory in RemoveMariogatchiFactory to get the action for releasing a Mariogatchi if the User does not want to catch it.

Otherwise, code looks great! Keep up the good work.

**Review by Grace199 — DISMISSED** [review]

**Review by vivekvzdsw — DISMISSED** [review]
Looks good and follows Clean Arch. maxLevel should go up by 10 but everything else is good.

**Review by adimaggio2021 — APPROVED** [review]
Good work

**Review by SpecialThing44 — APPROVED** [review]
Code looks good, will have to do more refactoring now :/

**Review by nishi003 — APPROVED** [review]
code looks good, are we still implementing rarity?

**Pull request merged**
